"""
Problem Understanding (Normalization) Layer
============================================

This module provides the normalization layer that sits BEFORE classification.

Core Principle:
- Classification must NEVER run on raw user text alone
- It runs on a normalized issue description generated by an LLM
- The LLM explains what the user is reporting
- The LLM does NOT decide call types, does NOT change state, does NOT route

Architecture Position:
    User Message
       ↓
    Problem Normalizer (LLM, constrained)  ← THIS MODULE
       ↓
    Canonical Issue Description
       ↓
    Existing Classifier (unchanged)
       ↓
    State Machine (unchanged)

CRITICAL CONSTRAINTS:
- The normalizer MUST NOT name call types (e.g., "10002", "Water Leak Code")
- The normalizer MUST NOT name departments (e.g., "Joburg Water", "City Power")
- The normalizer MUST NOT make routing decisions
- The normalizer ONLY describes the problem in plain municipal service language

Example Transformations:
- Input: "cables on the road"
  Output: "Electrical cables lying exposed on a public road, creating a safety hazard"

- Input: "seats are dirty" (after clarification: "bus seats")
  Output: "Unclean and unhygienic seats inside a public transport bus requiring cleaning"

- Input: "no water" (after clarification: "whole street affected, 2 days")
  Output: "Complete water supply outage affecting an entire street, ongoing for 2 days"
"""

from __future__ import annotations

import logging
from typing import Optional, List

import dspy

from src.conversation.case_memory import CaseMemory
from src.core.circuit_breaker import CircuitBreaker, CircuitBreakerOpen

logger = logging.getLogger(__name__)

# Circuit breaker for normalization calls
normalizer_circuit = CircuitBreaker(failure_threshold=3, recovery_timeout=30)


class NormalizeIssueDescription(dspy.Signature):
    """
    Transform user messages into a normalized municipal service issue description.
    
    CRITICAL INSTRUCTIONS FOR THE MODEL:
    
    1. DESCRIBE the problem in clear, municipal service language
    2. INFER reasonable context from the conversation
    3. DO NOT invent facts that weren't mentioned
    4. DO NOT mention call type codes, numbers, or IDs
    5. DO NOT mention department names or service provider names
    6. DO NOT decide which service should handle it
    7. FOCUS on: what is broken/missing/wrong, where (general context), severity
    
    GOOD EXAMPLES:
    - "Electrical cables lying exposed on a public road, creating a safety hazard"
    - "Water pipe burst on residential street causing flooding"
    - "Street light not functioning, creating darkness at night"
    - "Refuse bins not collected for over a week, waste accumulating"
    - "Unclean seats inside a public transport bus"
    
    BAD EXAMPLES (DO NOT DO THIS):
    - "Call Type 10002 - Water Leak" (mentions code)
    - "Report to Joburg Water department" (mentions department)
    - "Electricity issue for City Power" (mentions service provider)
    - "Category: Roads" (classifying instead of describing)
    
    YOUR TASK: Describe the problem neutrally and completely, as if explaining
    to a municipal services dispatcher who needs to understand WHAT is wrong,
    not WHO should handle it.
    """
    
    # Input fields
    user_message: str = dspy.InputField(
        desc="The current user message describing their issue"
    )
    conversation_history: str = dspy.InputField(
        desc="Previous messages from the conversation (if any), providing context"
    )
    
    # Output field
    normalized_description: str = dspy.OutputField(
        desc=(
            "A clear, complete description of the municipal service issue in plain language. "
            "Focus on WHAT is wrong (broken/leaking/missing/dirty/not working), "
            "WHERE it is (street/building/vehicle/facility - general context only), "
            "and HOW BAD it is (severity indicators). "
            "Do NOT mention call type codes, department names, or service categories."
        )
    )


# Base predictor (unwrapped)
_base_issue_normalizer = dspy.Predict(NormalizeIssueDescription)


@normalizer_circuit
def _safe_normalize_issue(user_message: str, conversation_history: str):
    """Wrapped normalizer with circuit breaker protection."""
    return _base_issue_normalizer(
        user_message=user_message,
        conversation_history=conversation_history
    )


def normalize_issue_description(
    user_message: str,
    memory: Optional[CaseMemory] = None
) -> str:
    """
    Normalize a user message into a canonical issue description.
    
    This is the public API for the normalization layer.
    
    Args:
        user_message: The current user message
        memory: Optional CaseMemory containing conversation history
    
    Returns:
        A normalized issue description suitable for classification,
        or the original user_message if normalization fails.
    
    Example:
        >>> normalize_issue_description("cables on the road", memory)
        "Electrical cables lying exposed on a public road, creating a safety hazard"
    
    Fallback Behavior:
        - If LLM fails: returns original user_message (safe degradation)
        - If circuit breaker open: returns original user_message
        - If result is empty: returns original user_message
    """
    # Build conversation history context
    # Accept either a CaseMemory/ContextMemory object or a plain list of messages
    conversation_history = ""
    if memory is None:
        messages = []
    elif hasattr(memory, "messages"):
        messages = memory.messages
    elif isinstance(memory, list):
        messages = memory
    else:
        messages = []

    if messages:
        recent_messages = messages[-3:]
        conversation_history = " | ".join(
            m if isinstance(m, str) else str(m) for m in recent_messages
        )
    
    try:
        # Call LLM normalizer
        result = _safe_normalize_issue(
            user_message=user_message,
            conversation_history=conversation_history
        )
        
        # Extract normalized description
        normalized = getattr(result, 'normalized_description', '').strip()
        
        # Validation: ensure we got something useful
        if not normalized:
            logger.warning("Normalization returned empty result, using original message")
            return user_message
        
        # Validation: ensure it's not too short (likely failed)
        if len(normalized) < 10:
            logger.warning("Normalization returned very short result, using original message")
            return user_message
        
        # Safety check: if normalized text is just repeating the input, skip
        if normalized.lower() == user_message.lower():
            logger.info("Normalization returned same as input, using original")
            return user_message
        
        logger.info(f"Normalized: '{user_message[:50]}...' → '{normalized[:50]}...'")
        return normalized
        
    except CircuitBreakerOpen:
        logger.warning("Normalizer circuit breaker open, using original message")
        return user_message
        
    except Exception as e:
        logger.warning(f"Normalization failed: {e}, using original message")
        return user_message


def normalize_with_clarifications(
    user_message: str,
    memory: CaseMemory,
    clarification_answers: Optional[List[str]] = None
) -> str:
    """
    Normalize an issue description including clarification answers.
    
    This is used when the user has answered clarification questions,
    and we want to build a complete normalized description from:
    - Original message
    - Clarification answers
    - Conversation context
    
    Args:
        user_message: The latest user message
        memory: CaseMemory with full conversation history
        clarification_answers: Specific answers to clarification questions (if any)
    
    Returns:
        A comprehensive normalized description incorporating all information
    
    Example:
        User: "seats are dirty"
        Clarification Q: "Where are these seats?"
        User: "on the bus"
        
        normalize_with_clarifications("on the bus", memory)
        → "Unclean and unhygienic seats inside a public transport bus"
    """
    # Build comprehensive history including clarification context
    conversation_history = ""
    if memory and memory.messages:
        # Include more messages when we have clarifications
        recent_messages = memory.messages[-5:] if clarification_answers else memory.messages[-3:]
        conversation_history = " | ".join(recent_messages)
        
        # Add explicit clarification answers if provided
        if clarification_answers:
            conversation_history += " | Clarifications: " + " | ".join(clarification_answers)
    
    try:
        result = _safe_normalize_issue(
            user_message=user_message,
            conversation_history=conversation_history
        )
        
        normalized = getattr(result, 'normalized_description', '').strip()
        
        if normalized and len(normalized) >= 10:
            logger.info(f"Normalized with clarifications: '{normalized[:60]}...'")
            return normalized
        
        # Fallback: try basic normalization
        return normalize_issue_description(user_message, memory)
        
    except Exception as e:
        logger.warning(f"Normalization with clarifications failed: {e}")
        return normalize_issue_description(user_message, memory)


__all__ = [
    "normalize_issue_description",
    "normalize_with_clarifications",
    "NormalizeIssueDescription",
]
