name: Build and Test Chatbot Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-analyze:
    uses: ./.github/workflows/local-build-test.yml
    with:
      node_js_version: '20.x'
      enable_sonarqube_quality_check: false