name: Local Terragrunt Plan

on:
  workflow_call:
    inputs:
      terragrunt_dir:
        required: true
        type: string
      terragrunt_version:
        required: true
        type: string
      terraform_version:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::905418043725:role/csd-cicd-role
          aws-region: af-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: ${{ inputs.terragrunt_version }}

      - name: Terragrunt Plan
        working-directory: ${{ inputs.terragrunt_dir }}
        env:
          TF_VAR_service_version: ${{ github.ref_type == 'branch' && github.sha || github.ref_name }}
          TERRAGRUNT_NON_INTERACTIVE: "true"
        run: |
          terragrunt plan -no-color -out=tfplan
