name: Terragrunt Plan

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  env-plans:
    strategy:
      matrix:
        component:
          - "non-prod/test/csd-chatbot"
          - "non-prod/qa/csd-chatbot"
          - "non-prod/uat/csd-chatbot"
          - "prod/prod/csd-chatbot"

    uses: ./.github/workflows/local-terragrunt-plan.yml
    with:
      terragrunt_dir: "./iac/${{ matrix.component }}"
      terragrunt_version: 0.68.6
      terraform_version: 1.9.5
    secrets: inherit
